const loginPanel=document.getElementById('login-panel'),dashboard=document.getElementById('dashboard'),editor=document.getElementById('editor'),loginForm=document.getElementById('login-form'),loginMessage=document.getElementById('login-message'),adminList=document.getElementById('admin-list'),writingForm=document.getElementById('writing-form'),editorHeading=document.getElementById('editor-heading');
let currentUser=null;
function configured(){return window.SUPABASE_CONFIG&&!window.SUPABASE_CONFIG.url.includes('YOUR-PROJECT')&&!window.SUPABASE_CONFIG.publishableKey.includes('YOUR_SUPABASE');}
async function boot(){if(!configured()){loginMessage.textContent='Connect Supabase in config.js first.';return;} const {data}=await sb.auth.getSession(); currentUser=data.session?.user??null; currentUser?showDashboard():showLogin(); sb.auth.onAuthStateChange((_e,s)=>{currentUser=s?.user??null;currentUser?showDashboard():showLogin();});}
function showDashboard(){loginPanel.classList.add('hidden');editor.classList.add('hidden');dashboard.classList.remove('hidden');renderList();}
function showLogin(){dashboard.classList.add('hidden');editor.classList.add('hidden');loginPanel.classList.remove('hidden');}
async function renderList(){adminList.innerHTML='<p class="empty-state">Loading…</p>'; const {data,error}=await sb.from('writings').select('id,title,date_label,published').order('created_at',{ascending:false}); if(error){adminList.innerHTML=`<p class="form-message">${esc(error.message)}</p>`;return;} adminList.innerHTML=data.length?data.map(w=>`<div class="admin-row"><div><strong>${esc(w.title)}</strong><small>${esc(w.date_label||'')} · ${w.published?'published':'draft'}</small></div><div class="row-actions"><button class="text-button" data-edit="${w.id}">Edit</button><button class="text-button danger" data-delete="${w.id}">Delete</button></div></div>`).join(''):'<p class="empty-state">No writings yet. Start with + New writing.</p>';}
async function openEditor(id=''){document.getElementById('editing-id').value=id;if(id){const {data,error}=await sb.from('writings').select('id,title,date_label,body,published').eq('id',id).maybeSingle();if(error||!data){alert('Could not load this writing.');return;}document.getElementById('writing-title').value=data.title;document.getElementById('writing-date').value=data.date_label||'';document.getElementById('writing-body').value=data.body;document.getElementById('writing-published').checked=data.published;editorHeading.textContent='Edit writing';}else{writingForm.reset();document.getElementById('writing-published').checked=true;editorHeading.textContent='New writing';}dashboard.classList.add('hidden');editor.classList.remove('hidden');}
function closeEditor(){editor.classList.add('hidden');dashboard.classList.remove('hidden');writingForm.reset();}
loginForm.addEventListener('submit',async e=>{e.preventDefault();loginMessage.textContent='Signing in…';const email=document.getElementById('email').value.trim(),password=document.getElementById('password').value;const {error}=await sb.auth.signInWithPassword({email,password});loginMessage.textContent=error?error.message:'';});
document.getElementById('logout').addEventListener('click',()=>sb.auth.signOut());
document.getElementById('new-writing').addEventListener('click',()=>openEditor());
document.getElementById('cancel-edit').addEventListener('click',closeEditor);document.getElementById('cancel-edit-2').addEventListener('click',closeEditor);
adminList.addEventListener('click',async e=>{const edit=e.target.dataset.edit,del=e.target.dataset.delete;if(edit)await openEditor(edit);if(del){const {data}=await sb.from('writings').select('title').eq('id',del).maybeSingle();if(data&&confirm(`Delete “${data.title}”? This cannot be undone.`)){const {error}=await sb.from('writings').delete().eq('id',del);if(error)alert(error.message);else renderList();}}});
writingForm.addEventListener('submit',async e=>{e.preventDefault();if(!currentUser)return;const id=document.getElementById('editing-id').value,title=document.getElementById('writing-title').value.trim(),date_label=document.getElementById('writing-date').value.trim()||null,body=document.getElementById('writing-body').value.trim(),published=document.getElementById('writing-published').checked;const payload={title,slug:slugify(title),date_label,body,published,author_id:currentUser.id};const result=id?await sb.from('writings').update(payload).eq('id',id).select().single():await sb.from('writings').insert(payload).select().single();if(result.error){alert(result.error.message);return;}closeEditor();renderList();});
function slugify(v){return v.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||`writing-${Date.now()}`;}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));}
boot();
